### ISSUE TITLE
In cart page, the map section coming in live is not coming in preview.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal-Christian-Speed-work#1]
**Actual result:**
In cart page, the map section coming in live is not coming in preview.
![image](https://user-images.githubusercontent.com/102131636/169640421-3d435c1a-e3e3-4d78-9527-89c2e14a7ae0.png)

**Expected result:**
The map section as coming in live have to come in preview also.
![image](https://user-images.githubusercontent.com/102131636/169640451-82cb026b-f674-4fac-bd68-b9006a75db65.png)

**Comment by devShivDuttChauhan** [comment]
![image](https://user-images.githubusercontent.com/103488177/169642193-579024de-97ab-4534-9238-9df9b0a843e2.png)
![image](https://user-images.githubusercontent.com/103488177/169642214-e83a3662-07d7-44b1-a8de-d6c4a02af931.png)

**Here Map is comming on Cart page kindly Check it Sir.... ISUUES are resolved.**
@sudhanshu0603

**Comment by sudhanshu0603** [comment]
ok, resolved
